salute-developers/plasma-android

.github/workflows/android-code-quality-check.yml

Code Quality Check workflow were changed

ci: Code Quality Check workflow.

---

sdds-core/icons/build.gradle.kts
sdds-core/icons/gradle.properties
sdds-core/icons/src/main/AndroidManifest.xml
sdds-core/settings.gradle.kts

Добавил модуль sdds-core:icons для иконок.

feat(sdds-acore/icons): Icons

---

.github/workflows/publish-icons.yml
build-system/conventions/src/main/kotlin/convention.auto-bump.gradle.kts
build-system/conventions/src/main/kotlin/utils/AutoBump.kt
sdds-core/icons/build.gradle.kts

Icon generation workflow was added.

build: Icon generation workflow.

---

sdds-core/uikit/src/main/kotlin/com/sdds/uikit/viewstate/ViewState.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/viewstate/ViewStateHolder.kt
sdds-core/uikit/src/main/res/values/attrs.xml

feat(sdds-acore/uikit): View state was added

---

.github/actions/maven-publish/action.yml
.github/workflows/build-release.yml
.github/workflows/create-tag-release.yml
.github/workflows/generate-icons.yml
.github/workflows/publish-icons-release.yml
build-system/build.gradle.kts
build-system/conventions/src/main/kotlin/convention.auto-bump.gradle.kts
build-system/conventions/src/main/kotlin/convention.maven-publish.gradle.kts
build-system/conventions/src/main/kotlin/convention.root-project.gradle.kts
build-system/conventions/src/main/kotlin/utils/AutoBump.kt

- Добавил workflows для публикации иконок

build: Icons publication

---

gradle/libs.versions.toml

Minimum sdk version was upgraded to 24.

build: Minimum SDK version upgrade

---

sdds-core/icons/gradle.properties

Icon develop version was incremented.

chore: Version increment.

---

.github/workflows/android-code-quality-check.yml
.github/workflows/build-debug.yml
.github/workflows/build-release.yml
.github/workflows/publish-theme-plugin-release.yml
.github/workflows/publish-uikit-compose-release.yml
.github/workflows/publish-uikit-release.yml

What changed: 
- Core libs release workflows were added.

ci: Release workflows.

---

.github/workflows/android-code-quality-check.yml
build-system/conventions/build.gradle.kts
build-system/conventions/src/main/kotlin/convention.compose-bom.gradle.kts
build-system/conventions/src/main/kotlin/convention.compose.gradle.kts
gradle/libs.versions.toml
sdds-core/plugin_theme_builder/build.gradle.kts
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/GenerateThemeTask.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/FontGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/GradientGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/TypographyGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/serializer/Serializer.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/utils/SerializationUtils.kt
sdds-core/plugin_theme_builder/src/test/kotlin/com/sdds/plugin/themebuilder/internal/generator/ColorGeneratorTest.kt
sdds-core/plugin_theme_builder/src/test/kotlin/com/sdds/plugin/themebuilder/internal/generator/FontGeneratorTest.kt
sdds-core/plugin_theme_builder/src/test/kotlin/com/sdds/plugin/themebuilder/internal/generator/GradientGeneratorTest.kt
sdds-core/plugin_theme_builder/src/test/kotlin/com/sdds/plugin/themebuilder/internal/generator/ShadowGeneratorTest.kt
sdds-core/plugin_theme_builder/src/test/kotlin/com/sdds/plugin/themebuilder/internal/generator/ShapeGeneratorTest.kt
sdds-core/plugin_theme_builder/src/test/kotlin/com/sdds/plugin/themebuilder/internal/generator/TypographyGeneratorTest.kt
sdds-core/plugin_theme_builder/src/test/kotlin/com/sdds/plugin/themebuilder/internal/utils/SerializationUtilsTest.kt
sdds-core/uikit-compose/build.gradle.kts
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/Utils.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/WindowSize.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/internal/LinearGradient.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/theme/CoreColors.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/theme/CoreGradients.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/theme/CoreShapes.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/theme/CoreTheme.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/theme/CoreTypography.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/theme/RippleTheme.kt

- Compose core theme was implemented;
- Kotlin version conflict was fixed.

feat(sdds-acore): Compose core theme.

---

sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/builder/KtFileBuilder.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/factory/ComposeShapeAttributeGeneratorFactory.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/factory/GeneratorFactory.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/ShapeGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/theme/ThemeGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/theme/compose/ComposeColorAttributeGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/theme/compose/ComposeShapeAttributeGenerator.kt
sdds-core/plugin_theme_builder/src/test/kotlin/com/sdds/plugin/themebuilder/internal/attributes/generator/ComposeShapeAttributeGeneratorTest.kt
sdds-core/plugin_theme_builder/src/test/resources/attrs-outputs/ColorsOutputKt.txt
sdds-core/plugin_theme_builder/src/test/resources/attrs-outputs/ShapesOutputKt.txt

* Реализовал генерацию атрибутов форм для compose
* Поправил видимость у LocalColors (сделал internal)

feat(sdds-acore/theme-builder): Generate compose shape attrs

---

sdds-core/uikit/src/main/kotlin/com/sdds/uikit/Button.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/ImageView.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/TextView.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/internal/base/shape/ShapeHelper.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/internal/base/shape/ShapeableImageDelegate.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/internal/focusselector/AnimatedSelectorDrawable.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/internal/focusselector/FocusSelectorMode.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/internal/focusselector/SelectorDrawable.kt
sdds-core/uikit/src/main/res/values/image_view_attrs.xml
sdds-core/uikit/src/main/res/values/text_view_attrs.xml

- TextView and ImageView were implemented. 
- Focus selector package were moved to internal package.

feat(sdds-acore/uikit): TextView and ImageView.

---

sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/factory/GeneratorFactory.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/factory/ViewGradientAttributeGeneratorFactory.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/ColorTokenGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/GradientGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/data/GradientTokenResult.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/theme/ThemeGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/theme/compose/ComposeGradientAttributeGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/theme/view/ViewGradientAttributeGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/theme/view/ViewThemeGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/token/ColorTokens.kt
sdds-core/plugin_theme_builder/src/test/kotlin/com/sdds/plugin/themebuilder/internal/attributes/generator/ComposeGradientAttributeGeneratorTest.kt
sdds-core/plugin_theme_builder/src/test/kotlin/com/sdds/plugin/themebuilder/internal/attributes/generator/ViewGradientAttributeGeneratorTest.kt
sdds-core/plugin_theme_builder/src/test/kotlin/com/sdds/plugin/themebuilder/internal/generator/GradientGeneratorTest.kt
sdds-core/plugin_theme_builder/src/test/kotlin/com/sdds/plugin/themebuilder/internal/generator/theme/ViewThemeGeneratorTest.kt
sdds-core/plugin_theme_builder/src/test/resources/attrs-outputs/gradient-attributes-output.xml
sdds-core/plugin_theme_builder/src/test/resources/theme-outputs/test-dark-theme-output.xml
sdds-core/plugin_theme_builder/src/test/resources/theme-outputs/test-theme-output.xml

* Реализовал генератор атрибутов градиентов для View System. Генерируются атрибуты для всех параметров градиента, а в светлой и темной теме устанавливаются соответствия атрибутов значениям.

feat(sdds-acore/theme-builder): Generate view system gradient attrs

---

playground/theme-builder/src/main/res/values/styles.xml
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/builder/KtFileBuilder.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/builder/XmlResourcesDocumentBuilder.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/factory/ComposeTypographyAttributeGeneratorFactory.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/factory/GeneratorFactory.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/factory/ViewThemeGeneratorFactory.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/ShapeGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/TypographyGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/data/TypographyTokenResult.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/theme/ThemeGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/theme/compose/ComposeColorAttributeGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/theme/compose/ComposeGradientAttributeGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/theme/compose/ComposeShapeAttributeGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/theme/compose/ComposeTypographyAttributeGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/theme/view/ViewThemeGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/theme/view/ViewTypographyAttributeGenerator.kt
sdds-core/plugin_theme_builder/src/test/kotlin/com/sdds/plugin/themebuilder/internal/attributes/generator/ComposeTypographyAttributeGeneratorTest.kt
sdds-core/plugin_theme_builder/src/test/kotlin/com/sdds/plugin/themebuilder/internal/attributes/generator/ViewTypographyAttributeGeneratorTest.kt
sdds-core/plugin_theme_builder/src/test/kotlin/com/sdds/plugin/themebuilder/internal/builder/KtFileBuilderTest.kt
sdds-core/plugin_theme_builder/src/test/kotlin/com/sdds/plugin/themebuilder/internal/builder/XmlResourcesDocumentBuilderTest.kt
sdds-core/plugin_theme_builder/src/test/kotlin/com/sdds/plugin/themebuilder/internal/generator/theme/ViewThemeGeneratorTest.kt
sdds-core/plugin_theme_builder/src/test/resources/attrs-outputs/TypographyOutputKt.txt
sdds-core/plugin_theme_builder/src/test/resources/theme-outputs/test-dark-theme-output.xml
sdds-core/plugin_theme_builder/src/test/resources/theme-outputs/test-theme-output.xml
sdds-core/plugin_theme_builder/src/test/resources/typography-outputs/TestTypographyOutputKt.txt

* Реализовал генератор атрибутов типографики для компоуз.
* Добавил рутовый стиль с названием resourcePrefix в темы для View.

feat(sdds-acore/theme-builder): Generate compose typography attrs

---

sdds-core/uikit/src/main/kotlin/com/sdds/uikit/Button.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/CheckBox.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/RadioBox.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/Switch.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/internal/CheckBoxDrawable.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/internal/CheckableDelegate.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/internal/RadioBoxDrawable.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/internal/SwitchDrawable.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/internal/base/Utils.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/internal/base/shape/ShapeHelper.kt
sdds-core/uikit/src/main/res/values/base_attrs.xml
sdds-core/uikit/src/main/res/values/checkable-attrs.xml

CheckBox, RadioBox and Switch were implemented.

feat(sdds-acore/uikit): CheckBox, RadioBox, Switch

---

playground/theme-builder/build.gradle.kts
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/builder/KtFileBuilder.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/factory/ComposeThemeGeneratorFactory.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/factory/ComposeTypographyAttributeGeneratorFactory.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/factory/GeneratorFactory.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/theme/ThemeGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/theme/compose/ComposeColorAttributeGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/theme/compose/ComposeThemeGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/theme/compose/ComposeTypographyAttributeGenerator.kt
sdds-core/plugin_theme_builder/src/main/resources/raw-kt-files/WindowSize.txt
sdds-core/plugin_theme_builder/src/test/kotlin/com/sdds/plugin/themebuilder/internal/attributes/generator/ComposeTypographyAttributeGeneratorTest.kt
sdds-core/plugin_theme_builder/src/test/kotlin/com/sdds/plugin/themebuilder/internal/builder/KtFileBuilderTest.kt
sdds-core/plugin_theme_builder/src/test/kotlin/com/sdds/plugin/themebuilder/internal/generator/theme/ComposeThemeGeneratorTest.kt
sdds-core/plugin_theme_builder/src/test/resources/attrs-outputs/ColorsOutputKt.txt
sdds-core/plugin_theme_builder/src/test/resources/theme-outputs/ThemeOutputKt.txt
sdds-core/plugin_theme_builder/src/test/resources/theme-outputs/ThemeOutputKtWithTextSelectionAndTextStyle.txt

* Реализовал генератор темы для Compose

feat(sdds-acore/theme-builder): Generate compose theme

---

sdds-core/uikit/src/main/kotlin/com/sdds/uikit/ProgressBar.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/Spinner.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/internal/base/drawable/SpinnerDrawable.kt
sdds-core/uikit/src/main/res/values/progress_attrs.xml

ProgressBar and Spinner were implemented

feat(sdds-acore/uikit): Progress indicators

---

sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/validator/LinearGradientTokenValidator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/validator/RadialGradientTokenValidator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/validator/SweepGradientTokenValidator.kt
sdds-core/plugin_theme_builder/src/test/kotlin/com/sdds/plugin/themebuilder/internal/validator/LinearGradientTokenValidatorTest.kt
sdds-core/plugin_theme_builder/src/test/kotlin/com/sdds/plugin/themebuilder/internal/validator/RadialGradientTokenValidatorTest.kt
sdds-core/plugin_theme_builder/src/test/kotlin/com/sdds/plugin/themebuilder/internal/validator/SweepGradientTokenValidatorTest.kt

* Добавил проверку на диапазон значений из locations в градиентах

fix(sdds-acore/theme-builder): Add lost gradient validation

---

.github/workflows/publish-all-tokens-release.yml
build-system/conventions/src/main/kotlin/convention.maven-publish.gradle.kts
build-system/conventions/src/main/kotlin/convention.root-project.gradle.kts
build-system/conventions/src/main/kotlin/tasks/MavenPublishTask.kt
build-system/conventions/src/main/kotlin/utils/NetworkUtils.kt
build-system/conventions/src/main/kotlin/utils/VersionHelper.kt
build-system/conventions/src/test/kotlin/utils/VersionHelperKtTest.kt

Publish all tokens workflow was implemented.

build: Publish tokens.

---

sdds-core/plugin_theme_builder/README.MD

* Актуализировал документацию theme-builder плагина.

docs(sdds-acore/theme-builder): Update readme

---

.github/workflows/publish-all-tokens-release.yml
build-system/conventions/src/main/kotlin/convention.maven-publish.gradle.kts
build-system/conventions/src/main/kotlin/convention.root-project.gradle.kts
build-system/conventions/src/main/kotlin/tasks/MavenPublishTask.kt
build-system/conventions/src/main/kotlin/utils/NetworkUtils.kt
build-system/conventions/src/main/kotlin/utils/VersionHelper.kt
build-system/conventions/src/test/kotlin/utils/VersionHelperKtTest.kt

Cherry-pick в main коммита https://github.com/salute-developers/plasma-android/commit/9c69c5551576e1a1e60f0a4038355e2816fc7069#diff-352bf7cc909e92370cb91e4485073bbf9b936f4cdb789f0a94f7f122b85f5b5e

build: Maven publish

---

build-system/conventions/src/main/kotlin/convention.compose-bom.gradle.kts
build-system/conventions/src/main/kotlin/convention.compose.gradle.kts
build-system/conventions/src/main/kotlin/convention.root-project.gradle.kts
gradle/libs.versions.toml
playground/sandbox/build.gradle.kts
playground/theme-builder/build.gradle.kts
tokens/build.gradle.kts
tokens/caldera.online.compose/build.gradle.kts
tokens/flamingo.compose/build.gradle.kts
tokens/plasma.b2c.compose/build.gradle.kts
tokens/plasma.web.compose/build.gradle.kts
tokens/sberhealth.compose/build.gradle.kts
tokens/sbermarket.business.compose/build.gradle.kts
tokens/sbermarket.compose/build.gradle.kts
tokens/sbermarket.metro.compose/build.gradle.kts
tokens/sbermarket.selgros.compose/build.gradle.kts
tokens/sbermarket.wlbusiness.compose/build.gradle.kts
tokens/sberonline.compose/build.gradle.kts
tokens/sberprime.compose/build.gradle.kts
tokens/sdds.serv.compose/build.gradle.kts
tokens/stylessalute.compose/build.gradle.kts

* bom compose исключен из зависимостей
* из mavenPublishAll исключены includedBuilds

fix(sdds-acore/theme-builder): Update compose token libs

---

sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/Text.kt

* Реализован компонент Text - обертка над BasicText

feat(sdds-acore/uikit-compose): Text component implemented

---

sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/Image.kt

* Реализован Image компонент на основе Image из foundation

feat(sdds-acore/uikit-compose): Image implemented

---

playground/sandbox/src/main/kotlin/com/sdds/playground/sandbox/SandboxActivity.kt
playground/sandbox/src/main/kotlin/com/sdds/playground/sandbox/buttons/SandboxButton.kt
playground/sandbox/src/main/kotlin/com/sdds/playground/sandbox/buttons/SandboxButtonSettingsProvider.kt
playground/sandbox/src/main/kotlin/com/sdds/playground/sandbox/checkbox/CheckBoxParametersViewModel.kt
playground/sandbox/src/main/kotlin/com/sdds/playground/sandbox/checkbox/CheckBoxUiState.kt
playground/sandbox/src/main/kotlin/com/sdds/playground/sandbox/checkbox/CheckBoxes.kt
playground/sandbox/src/main/kotlin/com/sdds/playground/sandbox/checkbox/SandboxCheckBox.kt
playground/sandbox/src/main/kotlin/com/sdds/playground/sandbox/checkbox/SandboxCheckBoxSettingsProvider.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/CheckBox.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/internal/Utils.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/internal/checkable/BaseCheckableLayout.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/internal/checkable/CheckBoxControl.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/internal/checkable/CheckBoxDefaults.kt

* Реализован CheckBox. Для текста использован компонент Text из uikit-compose.

feat(sdds-acore/uikit-compose): Implemented CheckBox for compose

---

playground/sandbox/src/main/kotlin/com/sdds/playground/sandbox/SandboxActivity.kt
playground/sandbox/src/main/kotlin/com/sdds/playground/sandbox/progress/ProgressScreen.kt
playground/sandbox/src/main/kotlin/com/sdds/playground/sandbox/progress/ProgressUiState.kt
playground/sandbox/src/main/kotlin/com/sdds/playground/sandbox/progress/ProgressViewModel.kt
playground/sandbox/src/main/kotlin/com/sdds/playground/sandbox/progress/SandboxProgress.kt
playground/sandbox/src/main/kotlin/com/sdds/playground/sandbox/progress/SandboxProgressSettingsProvider.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/Progress.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/internal/BaseProgress.kt

* Реализован Progress компонент

feat(sdds-acore/uikit-compose): Implemented Progress

---

sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/Progress.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/internal/BaseProgress.kt

* Добавил поддержку радиусов скруглений для бэкграунда и ндикатора в прогрессе
* Добавил обработку ситуации, когда прогресс = 0, индикатор в этом случае не рисуется

feat(sdds-acore/uikit-compose): Supported corner radius for Progress

---

sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/Progress.kt

* Исправил размер Progress, использовался неправильный экстеншен dp.

feat(sdds-acore/uikit-compose): Fix progress size

---

gradle/libs.versions.toml
playground/sandbox/build.gradle.kts
playground/sandbox/src/main/AndroidManifest.xml
playground/sandbox/src/main/kotlin/com/sdds/playground/sandbox/SandboxActivity.kt
playground/sandbox/src/main/kotlin/com/sdds/playground/sandbox/Theme.kt
playground/sandbox/src/main/kotlin/com/sdds/playground/sandbox/avatar/AvatarScreen.kt
playground/sandbox/src/main/kotlin/com/sdds/playground/sandbox/avatar/AvatarUiState.kt
playground/sandbox/src/main/kotlin/com/sdds/playground/sandbox/avatar/SandboxAvatar.kt
playground/sandbox/src/main/kotlin/com/sdds/playground/sandbox/avatar/SandboxAvatarParameterViewModel.kt
playground/sandbox/src/main/kotlin/com/sdds/playground/sandbox/avatar/SandboxAvatarSettingsProvider.kt
playground/sandbox/src/main/kotlin/com/sdds/playground/sandbox/core/ComponentScaffold.kt
playground/sandbox/src/main/res/drawable/il_avatar_test.xml
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/Avatar.kt

https://github.com/user-attachments/assets/99d29ec9-5b54-4ce1-98e7-c9c37f8ebb31

feat(sdds-acore/uikit-compose): Avatar.

---

playground/sandbox/src/main/kotlin/com/sdds/playground/sandbox/SandboxActivity.kt
playground/sandbox/src/main/kotlin/com/sdds/playground/sandbox/avatar/AvatarGroupScreen.kt
playground/sandbox/src/main/kotlin/com/sdds/playground/sandbox/avatar/AvatarScreen.kt
playground/sandbox/src/main/kotlin/com/sdds/playground/sandbox/avatar/AvatarUiState.kt
playground/sandbox/src/main/kotlin/com/sdds/playground/sandbox/avatar/SandboxAvatar.kt
playground/sandbox/src/main/kotlin/com/sdds/playground/sandbox/avatar/SandboxAvatarParameterViewModel.kt
playground/sandbox/src/main/kotlin/com/sdds/playground/sandbox/avatar/SandboxAvatarSettingsProvider.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/Avatar.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/AvatarGroup.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/internal/AvatarDefaults.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/internal/Utils.kt

AvatarGroup was implemented.
https://github.com/user-attachments/assets/c9af12ce-a135-424b-a726-0509c5f3b952

feat(sdds-acore/uikit-compose): AvatarGroup.

---

playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/SandboxActivity.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/theme/compose/ComposeColorAttributeGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/theme/compose/ComposeGradientAttributeGenerator.kt
sdds-core/plugin_theme_builder/src/test/resources/attrs-outputs/ColorsOutputKt.txt
sdds-core/plugin_theme_builder/src/test/resources/attrs-outputs/GradientsOutputKt.txt

* Сократил тело функций в атрибутах цвета и градиента

feat(sdds-acore/theme-builder): Reduce color and gradient functions

---

sdds-core/uikit/src/main/kotlin/com/sdds/uikit/Chip.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/drawable/ChipDrawable.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/drawable/ShapeDrawable.kt
sdds-core/uikit/src/main/res/values/chip_attrs.xml
sdds-core/uikit/src/main/res/values/styles_chip.xml
sdds-core/uikit/src/main/res/values/themes.xml

feat(sdds-acore/uikit): Chip.

---

playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/SandboxActivity.kt
playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/avatar/SandboxAvatar.kt
playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/checkbox/CheckBoxParametersViewModel.kt
playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/checkbox/group/CheckBoxGroupParametersViewModel.kt
playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/checkbox/group/CheckBoxGroupScreen.kt
playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/checkbox/group/CheckBoxGroupUiState.kt
playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/checkbox/group/SandboxCheckBoxGroup.kt
playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/checkbox/group/SandboxCheckBoxGroupSettingsProvider.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/AvatarGroup.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/CheckBoxGroup.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/RadioBox.kt

* Реализовал checkbox group.
* Предоставил два варианта апи: абстрактный контейнер, не привязанный к конкретному компоненту и обертка, которая содержит компонент CheckBox и сама управляет состояниями рутовый/дочерний чекбокс.
* Исправил проблему задваивания контента в AvatarGroup и в CheckBoxGroupContainer
https://github.com/user-attachments/assets/e6a3a541-f3bd-4a76-9458-7ccda1d9a0f4

feat(sdds-acore/uikit-compose): CheckBoxGroup was implemented

---

playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/SandboxActivity.kt
playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/chip/ChipParametersViewModel.kt
playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/chip/ChipScreen.kt
playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/chip/ChipUiState.kt
playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/chip/SandboxChip.kt
playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/chip/SandboxChipSettingsProvider.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/Chip.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/Icon.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/internal/common/ShapeableHorizontalContainer.kt

* Реализован Chip. Представляет собой горизонтальный контейнер произвольных элементов
* Сделал так, чтобы кор компонент знал о левом, правом и центральном контенте и отступах между ними.
Добавил Компоненты Icon с LocalTint. В чипе предоставляю LocalTint для лямбд с иконками и LocalTextStyle для текста
https://github.com/user-attachments/assets/f846777f-aa82-4cd2-80c4-abc3e1f4c91b

WIP feat(sdds-acore/uikit-compose): Chip was implemented

---

playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/textfield/SandboxTextField.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/TextField.kt

* Убрал внутренний label в размере XS
https://github.com/user-attachments/assets/b05d7864-c68f-442c-888e-21e8c8595c50

fix(sdds-acore/uikit-compose): Remove text field label when size is xs

---

sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/ThemeBuilderPlugin.kt

* Исправил поведение, при котором таска generateTheme и другие таски теряли возможность кешироваться gradle.

feature(sdds-acore/theme-builder): Fix plugin tasks caching

---

playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/SandboxActivity.kt
playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/chip/SandboxChip.kt
playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/chip/SandboxChipSettingsProvider.kt
playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/chip/group/ChipGroupParametersViewModel.kt
playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/chip/group/ChipGroupScreen.kt
playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/chip/group/ChipGroupUiState.kt
playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/chip/group/SandboxChipGroup.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/Chip.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/ChipGroup.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/internal/common/FlowRowLayout.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/internal/common/Modifiers.kt

* Реализовал chip group
* Добавил поведение toggleable для чипа (раньше он был как кнопка)
https://github.com/user-attachments/assets/a73b160d-6055-445d-81ae-63ee2c71d4a6

feat(sdds-acore/uikit-compose): Chip group was implemented

---

sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/Chip.kt
tokens/settings.gradle.kts

* Исправлен layout chip-компонента
https://github.com/user-attachments/assets/c031ed7f-932c-430b-9b41-17e7012ac121

fix(sdds-acore/uikit-compose): chip fix

---

playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/SandboxActivity.kt
playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/buttons/SandboxButtonSettingsProvider.kt
playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/textarea/SandboxTextArea.kt
playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/textarea/TextAreaDefaults.kt
playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/textarea/TextAreaScreen.kt
playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/textarea/TextAreaUiState.kt
playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/textarea/TextAreaViewModel.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/ScrollBar.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/TextArea.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/internal/textarea/BaseTextArea.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/internal/textarea/TextAreaDecorationBox.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/internal/textarea/TextAreaLayout.kt

* Реализован компонент text area
https://github.com/user-attachments/assets/e452e7c1-aa42-4d9f-aff1-f1be0ed3f259

feat(sdds-acore/uikit-compose): text area was implemented

---

sdds-core/uikit-compose/gradle.properties

fix(sdds-acore/uikit-compose): bump uikit-compose version

---

sdds-core/icons/gradle.properties
sdds-core/plugin_theme_builder/gradle.properties
sdds-core/uikit-compose/gradle.properties

* Актуализированы неактуальные версии библиотек

chore(sdds-android/build-system): update versions

---

playground/sandbox/src/main/kotlin/com/sdds/playground/sandbox/SandboxActivity.kt
playground/sandbox/src/main/kotlin/com/sdds/playground/sandbox/buttons/BasicButtonFragment.kt
playground/sandbox/src/main/kotlin/com/sdds/playground/sandbox/buttons/IconButtonFragment.kt
playground/sandbox/src/main/kotlin/com/sdds/playground/sandbox/checkbox/CheckBoxFragment.kt
playground/sandbox/src/main/kotlin/com/sdds/playground/sandbox/chip/ChipFragment.kt
playground/sandbox/src/main/kotlin/com/sdds/playground/sandbox/chip/ChipParametersViewModel.kt
playground/sandbox/src/main/kotlin/com/sdds/playground/sandbox/chip/ChipUiState.kt
playground/sandbox/src/main/kotlin/com/sdds/playground/sandbox/chip/group/ChipGroupFragment.kt
playground/sandbox/src/main/kotlin/com/sdds/playground/sandbox/core/view/ComponentFragment.kt
playground/sandbox/src/main/kotlin/com/sdds/playground/sandbox/radiobox/RadioBoxFragment.kt
playground/sandbox/src/main/res/layout/fragment_component_scaffold.xml
playground/sandbox/src/main/res/menu/activity_main_drawer.xml
playground/sandbox/src/main/res/navigation/sandbox_graph.xml
playground/sandbox/src/main/res/values-night/themes.xml
playground/sandbox/src/main/res/values/components_ids.xml
playground/sandbox/src/main/res/values/overlays_chip.xml
playground/sandbox/src/main/res/values/strings.xml
playground/sandbox/src/main/res/values/styles_chip.xml
playground/sandbox/src/main/res/values/themes.xml
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/Chip.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/ChipGroup.kt
sdds-core/uikit/src/main/res/values/chip_attrs.xml
sdds-core/uikit/src/main/res/values/styles_chip.xml

ChipGroup was implemented and added to sandbox.
https://github.com/user-attachments/assets/c4a664fa-b9c0-4cfc-a220-9ad1ff3a2d5f

feat(sdds-acore/uikit): ChipGroup.

---

.github/workflows/build-debug.yml
playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/SandboxActivity.kt
playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/textarea/SandboxTextArea.kt
playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/textarea/TextAreaDefaults.kt
playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/textarea/TextAreaScreen.kt
playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/textarea/TextAreaUiState.kt
playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/textarea/TextAreaViewModel.kt
playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/textfield/SandboxTextField.kt
playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/textfield/TextFieldScreen.kt
playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/textfield/TextFieldUiState.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/TextArea.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/internal/common/Modifiers.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/internal/textarea/BaseTextArea.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/internal/textarea/TextAreaDecorationBox.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/internal/textarea/TextAreaLayout.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/internal/textfield/common/DotBadge.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/internal/textfield/common/Label.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/internal/textfield/common/LayoutUtils.kt

* Отменил изменения из https://github.com/salute-developers/plasma-android/pull/129

feat(sdds-acore/uikit-compose): revert text field refactoring

---

sdds-core/uikit-compose/gradle.properties
sdds-core/uikit/gradle.properties

* Бамп версий uikit-compose и uikit

chore: bump uikit-compose and uikit version

---

playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/textfield/SandboxTextField.kt
playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/textfield/TextFieldScreen.kt
playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/textfield/TextFieldUiState.kt
playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/textfield/TextFieldViewModel.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/TextField.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/internal/textfield/PrefixSuffixTransformation.kt

* Реализовал поддержку перфикса и суффкиса с помощью VisualTransformation

feat(sdds-acore/uikit-compose): prefix and suffix were implemented

---

.github/workflows/generate-icons.yml

* Сделал отведение релизной ветки с иконками от main, а не от develop

ci: Create icons PR from main

---

playground/sandbox/src/main/res/color-night/bg_color_property_switch_track.xml
playground/sandbox/src/main/res/color-night/bg_property_item.xml
playground/sandbox/src/main/res/color-night/color_property_item_label.xml
playground/sandbox/src/main/res/color-night/color_property_item_value.xml
playground/sandbox/src/main/res/color/bg_color_property_switch_track.xml
playground/sandbox/src/main/res/color/bg_property_item.xml
playground/sandbox/src/main/res/color/bg_textfield_box.xml
playground/sandbox/src/main/res/color/color_property_item_label.xml
playground/sandbox/src/main/res/color/color_property_item_value.xml
playground/sandbox/src/main/res/color/color_textfield_caption.xml
playground/sandbox/src/main/res/color/color_textfield_placeholder.xml
playground/sandbox/src/main/res/layout/layout_switch_property_item.xml
playground/sandbox/src/main/res/layout/layout_value_property_item.xml
playground/sandbox/src/main/res/values/styles_text_area.xml
playground/sandbox/src/main/res/values/styles_text_field.xml
playground/sandbox/src/main/res/values/themes.xml
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/Avatar.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/TextField.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/drawable/ChipDrawable.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/internal/CheckBoxDrawable.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/internal/CheckableDelegate.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/internal/RadioBoxDrawable.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/internal/SwitchDrawable.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/internal/base/Utils.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/internal/base/drawable/SpinnerDrawable.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/internal/textfield/DecoratedFieldBox.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/internal/textfield/StatefulEditText.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/shape/ShapeDrawable.kt

Antialiasing was added to components. TextField focus was fixed. Some minor fixes were added.

fix(sdds-acore/uikit): UIKit Bugfixes

---

playground/sandbox/src/main/res/values/themes.xml
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/TypographyTokenGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/theme/compose/ComposeTypographyAttributeGenerator.kt
sdds-core/plugin_theme_builder/src/test/kotlin/com/sdds/plugin/themebuilder/internal/generator/TypographyTokenGeneratorTest.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/Button.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/Chip.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/ImageView.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/TextField.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/TextView.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/internal/base/shape/ShapeHelper.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/internal/base/shape/Shapeable.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/internal/base/shape/ShapeableImageDelegate.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/internal/focusselector/AnimatedSelectorDrawable.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/internal/focusselector/FocusScaleAnimationHelper.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/internal/focusselector/FocusSelectorMode.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/internal/focusselector/HasFocusSelector.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/internal/focusselector/SelectorDrawable.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/internal/textfield/DecoratedFieldBox.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/shape/ShapeDrawable.kt
sdds-core/uikit/src/main/res/values/base_attrs.xml
sdds-core/uikit/src/main/res/values/styles_avatar.xml

-FocusSelector was improved. 
-FocusSelectorMode.SCALE was implemented.
https://github.com/user-attachments/assets/8cb3659a-9a83-4f17-b445-e6a91fa96aae

feat(sdds-acore/uikit): FocusSelector.

---

sdds-core/uikit/gradle.properties

UiKit version was incremented.

chore(sdds-acore/uikit): Bump version.

---

.github/workflows/publish-sandbox-compose.yml
.github/workflows/publish-sandbox.yml
build-system/conventions/src/main/kotlin/convention.android-app.gradle.kts

* Workflows publish-sandbox and publish sandbox-compose was added, signingConfigs in buldTypes was added.

ci(sdds-android/github): Workflows for publishing was added

---

playground/sandbox/src/main/res/values-night/themes.xml
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/Chip.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/ProgressBar.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/internal/focusselector/AnimatedSelectorDrawable.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/internal/focusselector/FocusScaleAnimationHelper.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/internal/focusselector/HasFocusSelector.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/internal/focusselector/SelectorDrawable.kt

Chip's drawable state was extended with checked state. ProgressBar animation was improved. FocusSelector instets were fixed.

fix(sdds-acore/uikit): Chip, Progress and FocusSelector fixes.

---

sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/builder/KtFileBuilder.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/TypographyTokenGenerator.kt
sdds-core/plugin_theme_builder/src/test/kotlin/com/sdds/plugin/themebuilder/internal/builder/KtFileBuilderTest.kt
sdds-core/plugin_theme_builder/src/test/resources/typography-outputs/TestTypographyOutputKt.txt

in TipographyTokenGenerator was added. Test for addSuppresAnnotation(warningName: String) was added.

feat(sdds-acore/theme-builder):Suppressing annotation function 

---

playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/checkbox/CheckBoxPreviews.kt
playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/checkbox/group/CheckBoxGroupParametersViewModel.kt
playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/checkbox/group/CheckBoxGroupScreen.kt
playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/checkbox/group/CheckBoxGroupUiState.kt
playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/checkbox/group/SandboxCheckBoxGroup.kt
playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/radiobox/RadioBoxPreviews.kt
playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/radiobox/group/RadioBoxGroupParametersViewModel.kt
playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/radiobox/group/RadioBoxGroupScreen.kt
playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/radiobox/group/RadioBoxGroupUiState.kt
playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/radiobox/group/SandboxRadioBoxGroup.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/CheckBoxGroup.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/RadioBox.kt
tokens/plasma.sd.service.sandbox.compose/src/main/kotlin/com/sdds/plasma/sd/service/sandbox/checkbox/CheckBoxPreviews.kt
tokens/plasma.sd.service.sandbox.compose/src/main/kotlin/com/sdds/plasma/sd/service/sandbox/checkbox/group/CheckBoxGroupParametersViewModel.kt
tokens/plasma.sd.service.sandbox.compose/src/main/kotlin/com/sdds/plasma/sd/service/sandbox/checkbox/group/CheckBoxGroupScreen.kt
tokens/plasma.sd.service.sandbox.compose/src/main/kotlin/com/sdds/plasma/sd/service/sandbox/checkbox/group/CheckBoxGroupUiState.kt
tokens/plasma.sd.service.sandbox.compose/src/main/kotlin/com/sdds/plasma/sd/service/sandbox/checkbox/group/SandboxCheckBoxGroup.kt
tokens/plasma.sd.service.sandbox.compose/src/main/kotlin/com/sdds/plasma/sd/service/sandbox/radiobox/RadioBoxPreviews.kt
tokens/plasma.sd.service.sandbox.compose/src/main/kotlin/com/sdds/plasma/sd/service/sandbox/radiobox/group/RadioBoxGroupParametersViewModel.kt
tokens/plasma.sd.service.sandbox.compose/src/main/kotlin/com/sdds/plasma/sd/service/sandbox/radiobox/group/RadioBoxGroupScreen.kt
tokens/plasma.sd.service.sandbox.compose/src/main/kotlin/com/sdds/plasma/sd/service/sandbox/radiobox/group/RadioBoxGroupUiState.kt
tokens/plasma.sd.service.sandbox.compose/src/main/kotlin/com/sdds/plasma/sd/service/sandbox/radiobox/group/SandboxRadioBoxGroup.kt

* Избавил Checkbox Group / Radiobox Group от data классов в апи

feat(sdds-acore/uikit-compose): radiobox group and checkbox group were refactored

---

sdds-core/plugin_theme_builder/gradle.properties
sdds-core/uikit-compose/gradle.properties
sdds-core/uikit/gradle.properties
tokens/plasma.sd.service.compose/gradle.properties

* Бамп версий uikit, uikit-compose, plugin-theme-builder, plasma-sd-service

chore(sdds-acore/uikit): bump themeBuilder, uikit, plasma-sd-service

---

sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/interactions/InteractiveColor.kt

InteractiveColor now can handle state combinations.

bugfix(sdds-acore/uikit-compose): InteractiveColor

---

playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/Theme.kt
playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/textfield/TextFieldScreen.kt
sdds-core/plugin_theme_builder/gradle.properties
sdds-core/uikit-compose/gradle.properties
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/Chip.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/internal/BaseButton.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/internal/focusselector/Border.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/internal/focusselector/FocusSelector.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/internal/focusselector/FocusSelectorMode.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/internal/textfield/BaseTextField.kt
sdds-core/uikit/gradle.properties
tokens/plasma.sd.service.compose/gradle.properties
tokens/plasma.sd.service.compose/src/main/kotlin/com/sdds/plasma/sd/service/tokens/compose/TypographyTokens.kt
tokens/plasma.sd.service.sandbox.compose/src/main/kotlin/com/sdds/plasma/sd/service/sandbox/Theme.kt
tokens/plasma.sd.service.sandbox.compose/src/main/kotlin/com/sdds/plasma/sd/service/sandbox/textfield/TextFieldScreen.kt

* Добавил focus selector в compose
https://github.com/user-attachments/assets/844680ef-2333-4181-a127-d3129881b441
https://github.com/user-attachments/assets/6dba668b-973d-4b31-942d-7ccbe174ff98

feat(sdds-acore/uikit-compose): focus selector was implemented

---

tokens/plasma.sd.service.compose/src/main/kotlin/com/sdds/plasma/sd/service/tokens/compose/PlasmaSdServiceShapes.kt
tokens/plasma.sd.service.compose/src/main/kotlin/com/sdds/plasma/sd/service/tokens/compose/PlasmaSdServiceTheme.kt
tokens/plasma.sd.service.compose/src/main/kotlin/com/sdds/plasma/sd/service/tokens/compose/PlasmaSdServiceTypography.kt

* Апдейт исходников plasma-sd-service

feat(sdds-alibs/plasma-sd-service): dimensions update

---

sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/SwitchStyle.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/internal/checkable/RadioBoxControl.kt

Switch color animation was disabled. Radiobox paddings were fixed.

fix(sdds-acore/uikit-compose): Compose Bugfixes.

---

sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/theme/compose/ComposeColorAttributeGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/theme/compose/ComposeGradientAttributeGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/theme/compose/ComposeTypographyAttributeGenerator.kt
sdds-core/plugin_theme_builder/src/test/resources/attrs-outputs/TypographyOutputKt_3.txt
tokens/plasma.sd.service.view/build.gradle.kts
tokens/stylessalute.compose/build.gradle.kts
tokens/stylessalute.view/build.gradle.kts

* Добавляю импорты только на те токены, которые необходимы

fix(sdds-acore/theme-builder): add token imports only if necessary

---

sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/GenerateComponentConfigsTask.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/components/ViewComponentStyleGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/components/button/BasicButtonStyleGeneratorView.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/components/button/IconButtonStyleGeneratorView.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/components/button/LinkButtonStyleGeneratorView.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/factory/ComponentStyleGeneratorFactory.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/ShapeTokenGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/TypographyTokenGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/theme/view/ViewThemeGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/token/ShapeToken.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/token/TypographyTokens.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/utils/FileProvider.kt
sdds-core/plugin_theme_builder/src/test/kotlin/com/sdds/plugin/themebuilder/internal/components/button/BasicButtonStyleGeneratorViewTest.kt
sdds-core/plugin_theme_builder/src/test/kotlin/com/sdds/plugin/themebuilder/internal/components/button/IconButtonStyleGeneratorViewTest.kt
sdds-core/plugin_theme_builder/src/test/kotlin/com/sdds/plugin/themebuilder/internal/components/button/LinkButtonStyleGeneratorViewTest.kt
sdds-core/plugin_theme_builder/src/test/resources/component-outputs/styles-basic-button.xml
sdds-core/plugin_theme_builder/src/test/resources/component-outputs/styles-icon-button.xml
sdds-core/plugin_theme_builder/src/test/resources/component-outputs/styles-link-button.xml
sdds-core/plugin_theme_builder/src/test/resources/theme-outputs/test-many-theme-output.xml
sdds-core/plugin_theme_builder/src/test/resources/theme-outputs/test-material-theme-output.xml
sdds-core/plugin_theme_builder/src/test/resources/theme-outputs/test-theme-output.xml

BasicButton, IconButton and LinkButton size vartiant style generators were implemented.

feat(sdds-acore/theme-builder): Button size generator.

---

sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/internal/textfield/BaseTextField.kt

* Исправил некорректное размещение counter в случае, когда caption отсутствует
https://github.com/user-attachments/assets/8f120464-5c65-4c69-a193-afb4381937ae

feat(sdds-acore/uikit-compose): fix text field counter

---

sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/TextFieldStyle.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/internal/textfield/BaseTextField.kt

* Сделал все цвета text-field интерактивными
* Доработал билдер цветов text-field, чтобы каждый метод возвращал билдер. Все работало без этого, потому что в стилях цвета применялись через apply

feat(sdds-acore/uikit-compose): make all text field colors interactive

---

playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/textfield/TextFieldUiState.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/interactions/ActivateInteraction.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/interactions/InteractiveColor.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/internal/textfield/BaseTextField.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/internal/textfield/TextFieldLayout.kt
tokens/plasma.sd.service.compose/src/main/kotlin/com/sdds/plasma/sd/service/styles/textfield/TextFieldStyles.kt
tokens/plasma.sd.service.compose/src/main/kotlin/com/sdds/plasma/sd/service/styles/textfield/clear/TextFieldClearStyles.kt
tokens/sdds.serv.compose/src/main/kotlin/com/sdds/serv/styles/textfield/TextFieldStyles.kt
tokens/sdds.serv.compose/src/main/kotlin/com/sdds/serv/styles/textfield/clear/TextFieldClearStyles.kt

* Перевел TextField c Column на Layout, чтобы поддержать применение к компоненту модификаторов размеров: fillMaxWidth(), wrapContentWidth(), width(), fillMaxHeight(), wrapContentHeight(), height() и т д...
* Добавил поддержку active состояния

feat(sdds-acore/uikit-compose): size modifiers were supported in TF

---

tokens/plasma.sd.service.compose/src/main/kotlin/com/sdds/plasma/sd/service/styles/textarea/TextAreaStyles.kt
tokens/plasma.sd.service.compose/src/main/kotlin/com/sdds/plasma/sd/service/styles/textarea/clear/TextAreaClearStyles.kt
tokens/plasma.sd.service.compose/src/main/kotlin/com/sdds/plasma/sd/service/styles/textfield/clear/TextFieldClearStyles.kt
tokens/sdds.serv.compose/src/main/kotlin/com/sdds/serv/styles/textarea/TextAreaStyles.kt
tokens/sdds.serv.compose/src/main/kotlin/com/sdds/serv/styles/textarea/clear/TextAreaClearStyles.kt
tokens/sdds.serv.compose/src/main/kotlin/com/sdds/serv/styles/textfield/clear/TextFieldClearStyles.kt

Перегенерированы стили в соответствии с обновленными конфигами

fix(sdds-acore/uikit-compose): update text field styles

---

sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/GenerateComponentConfigsTask.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/components/base/BaseConfig.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/components/button/ButtonConfig.kt

* Сделал модель для парсинга конфигов кнопок

feat(sdds-acore/theme-builder): create new button config

---

playground/sandbox-compose/src/main/res/navigation/sandbox_graph.xml
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/IconButton.kt

- Исправил выключение текста в IconButton
- Поменял заголовок экрана IconButton

fix(sdds-acore/uikit): IconButton text disabling was fixed

---

playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/core/compose/Editors.kt
playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/textfield/compose/TextFieldScreen.kt
playground/sandbox-compose/src/main/res/values/strings.xml
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/TextField.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/interactions/ActivateInteraction.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/internal/focusselector/FocusSelectorMode.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/internal/textfield/BaseTextField.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/internal/textfield/DecorationBox.kt
tokens/plasma.sd.service.compose/src/main/kotlin/com/sdds/plasma/sd/service/styles/textarea/TextAreaStyles.kt
tokens/plasma.sd.service.compose/src/main/kotlin/com/sdds/plasma/sd/service/styles/textarea/clear/TextAreaClearStyles.kt
tokens/plasma.sd.service.compose/src/main/kotlin/com/sdds/plasma/sd/service/styles/textfield/TextFieldStyles.kt
tokens/plasma.sd.service.compose/src/main/kotlin/com/sdds/plasma/sd/service/styles/textfield/clear/TextFieldClearStyles.kt
tokens/sdds.serv.compose/src/main/kotlin/com/sdds/serv/styles/textarea/TextAreaStyles.kt
tokens/sdds.serv.compose/src/main/kotlin/com/sdds/serv/styles/textarea/clear/TextAreaClearStyles.kt
tokens/sdds.serv.compose/src/main/kotlin/com/sdds/serv/styles/textfield/TextFieldStyles.kt
tokens/sdds.serv.compose/src/main/kotlin/com/sdds/serv/styles/textfield/clear/TextFieldClearStyles.kt

* Доработал поведение фокуса в text field
* Добавил вариант TextField с value: String, вместо value: TextFieldValue
* Поправил область кликабельности
* Сгенерировал новые стили в библиотеках после апдейтов в конфиге text field
https://github.com/user-attachments/assets/9d68c253-f07c-4249-8cac-e30261b26122

feat(sdds-acore/uikit-compose): text field focus improvements. style updates.

---

gradle/libs.versions.toml
playground/sandbox-compose/gradle.properties
sdds-core/uikit-compose/gradle.properties
sdds-core/uikit/gradle.properties
tokens/plasma.sd.service.compose/gradle.properties
tokens/sdds.serv.compose/gradle.properties
tokens/sdds.serv.view/gradle.properties

chore: bump versions

---

playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/textfield/compose/TextFieldScreen.kt
playground/sandbox-compose/src/test/kotlin/com/sdds/playground/sandbox/compose/ComposeTextFieldScreenshotTest.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/TextField.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/internal/textfield/BaseTextField.kt
tokens/plasma.sd.service.sandbox.compose/src/test/kotlin/com/sdds/plasma/sd/service/ComposeTextFieldScreenshotTest.kt

Исправил фокус и accessibility в text field. 
https://github.com/user-attachments/assets/2b0b75cd-43c1-4f5b-aa76-dec3c6f5f9c2

feat(sdds-acore/uikit-compose): text field accessibility was fixed

---

sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/builder/KtFileBuilder.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/factory/ComposeShadowAttributeGeneratorFactory.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/factory/GeneratorFactory.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/ShadowTokenGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/theme/ThemeGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/theme/compose/ComposeShadowAttributeGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/theme/compose/ComposeThemeGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/token/Token.kt
sdds-core/plugin_theme_builder/src/test/kotlin/com/sdds/plugin/themebuilder/internal/generator/ShadowTokenGeneratorTest.kt
sdds-core/plugin_theme_builder/src/test/resources/shadow-outputs/TestShadowOutputKt.txt
sdds-core/plugin_theme_builder/src/test/resources/theme-outputs/ThemeOutputKt.txt
sdds-core/plugin_theme_builder/src/test/resources/theme-outputs/ThemeOutputKtWithTextSelectionAndTextStyle.txt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/shadow/Shadows.kt

- Реализовал тени на compose
- Реализовал генератор теней для compose

feat: Compose shadows

---

sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/GenerateThemeTask.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/ThemeBuilderPlugin.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/factory/ComposeSpacingAttributeGeneratorFactory.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/factory/GeneratorFactory.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/factory/ViewSpacingAttributeGeneratorFactory.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/SpacingTokenGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/data/SpacingTokenResult.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/theme/ThemeGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/theme/compose/ComposeSpacingAttributeGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/theme/compose/ComposeThemeGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/theme/view/ViewSpacingAttributeGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/theme/view/ViewThemeGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/serializer/Serializer.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/token/SpacingToken.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/utils/FileProvider.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/validator/SpacingTokenValidator.kt
sdds-core/plugin_theme_builder/src/test/kotlin/com/sdds/plugin/themebuilder/internal/generator/SpacingTokenGeneratorTest.kt
sdds-core/plugin_theme_builder/src/test/kotlin/com/sdds/plugin/themebuilder/internal/utils/SerializationUtilsTest.kt
sdds-core/plugin_theme_builder/src/test/resources/inputs/test-spacing-input.json
sdds-core/plugin_theme_builder/src/test/resources/inputs/test-spacing-value-input.json
sdds-core/plugin_theme_builder/src/test/resources/spacing-outputs/TestSpacingFromResourceOutputKt.txt
sdds-core/plugin_theme_builder/src/test/resources/spacing-outputs/TestSpacingOutputKt.txt
sdds-core/plugin_theme_builder/src/test/resources/spacing-outputs/test-spacing-output.xml
sdds-core/plugin_theme_builder/src/test/resources/theme-outputs/ThemeOutputKt.txt
sdds-core/plugin_theme_builder/src/test/resources/theme-outputs/ThemeOutputKtWithTextSelectionAndTextStyle.txt

Spacing tokens generator was implemented.

feat(sdds-acore/theme-builder): Spacing tokens.

---

playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/activities/vs/SandboxActivity.kt
playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/indicator/vs/IndicatorFragment.kt
playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/indicator/vs/IndicatorParametersViewModel.kt
playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/indicator/vs/IndicatorUiState.kt
playground/sandbox-compose/src/main/res/menu/activity_main_drawer.xml
playground/sandbox-compose/src/main/res/navigation/sandbox_graph.xml
playground/sandbox-compose/src/main/res/values/components_ids.xml
playground/sandbox-compose/src/main/res/values/strings.xml
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/GenerateComponentConfigsTask.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/ThemeBuilderPlugin.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/components/indicator/IndicatorConfig.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/components/indicator/view/IndicatorStyleGeneratorView.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/factory/ComponentStyleGeneratorFactory.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/Indicator.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/TextField.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/drawable/IndicatorDrawable.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/internal/textfield/IndicatorTextFieldDrawable.kt
sdds-core/uikit/src/main/res/values/indicator_attrs.xml
sdds-core/uikit/src/main/res/values/styles_indicator.xml
sdds-core/uikit/src/main/res/values/themes.xml
tokens/sdds.serv.view/src/main/kotlin/com/sdds/serv/colorstate/IndicatorColorState.kt
tokens/sdds.serv.view/src/main/theme-builder-res/color/serv_indicator_bg_color.xml
tokens/sdds.serv.view/src/main/theme-builder-res/values/indicator-attributes.xml
tokens/sdds.serv.view/src/main/theme-builder-res/values/style-dimens.xml
tokens/sdds.serv.view/src/main/theme-builder-res/values/styles-indicator.xml
tokens/sdds.serv.view/src/main/theme-builder-res/values/theme.xml

Generator for Indicator (view system) was added

feat(sdds-acore/uikit):Component Indicator was added

---

sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/components/base/compose/ComposeVariationGenerator.kt

fix(sdds-acore/theme-builder): default variation was added

---

playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/segment/compose/SegmentItemScreen.kt
playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/segment/compose/SegmentScreen.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/SegmentItem.kt
tokens/plasma-stards-compose/src/main/kotlin/com/sdkit/star/designsystem/styles/segment/item/SegmentItemStyles.kt

* Исправил цвет valueColor в SegmentItem для библиотеки stards

fix(sdds-alibs/stards): fix segment item value colors

---

playground/sandbox-plasma-giga-app-integration/src/main/kotlin/com/sdds/playground/sandbox/plasma/giga/app/integration/PlasmaGigaAppComposeComponents.kt
playground/sandbox-plasma-giga-app-integration/src/main/kotlin/com/sdds/playground/sandbox/plasma/giga/app/integration/bottomsheet/PlasmaGigaAppBottomSheetVariationsCompose.kt
playground/sandbox-plasma-giga-app-integration/src/main/kotlin/com/sdds/playground/sandbox/plasma/giga/app/integration/divider/compose/PlasmaGigaAppDividerVariationsCompose.kt
playground/sandbox-plasma-giga-integration/src/main/kotlin/com/sdds/playground/sandbox/plasma/giga/integration/PlasmaGigaComposeComponents.kt
playground/sandbox-plasma-giga-integration/src/main/kotlin/com/sdds/playground/sandbox/plasma/giga/integration/divider/compose/PlasmaGigaDividerVariationsCompose.kt
tokens/plasma.giga.app.compose/gradle.properties
tokens/plasma.giga.app.compose/src/main/kotlin/com/sdds/plasma/giga/app/styles/bottomsheet/ModalBottomSheet.kt
tokens/plasma.giga.app.compose/src/main/kotlin/com/sdds/plasma/giga/app/styles/bottomsheet/ModalBottomSheetStyles.kt
tokens/plasma.giga.compose/src/main/kotlin/com/sdds/plasma/giga/styles/basicbutton/BasicButtonStyles.kt
tokens/plasma.giga.compose/src/main/kotlin/com/sdds/plasma/giga/styles/iconbutton/IconButtonStyles.kt

* Добавил bottom-sheet и divider в plasma-giga / giga-app
* Вернул фикс бэкграунда clear кнопки в plasma-giga

fix(sdds-alibs/plasma-giga-app): lost styles were added

---

sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/GenerateComponentsTask.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/components/base/BaseConfig.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/components/base/compose/ComposeVariationGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/components/base/view/ColorStateListGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/components/base/view/NumberStateListGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/components/base/view/ValueStateListGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/components/base/view/ViewComponentStyleGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/components/base/view/ViewVariationGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/factory/ColorStateListGeneratorFactory.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/factory/NumberStateListGeneratorFactory.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/serializer/Serializer.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/utils/FileProvider.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/utils/ResourceReferenceProvider.kt
sdds-core/plugin_theme_builder/src/test/kotlin/com/sdds/plugin/themebuilder/internal/components/button/view/BasicButtonStyleGeneratorViewTest.kt
sdds-core/plugin_theme_builder/src/test/kotlin/com/sdds/plugin/themebuilder/internal/components/button/view/IconButtonStyleGeneratorViewTest.kt
sdds-core/plugin_theme_builder/src/test/kotlin/com/sdds/plugin/themebuilder/internal/components/button/view/LinkButtonStyleGeneratorViewTest.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/graphics/LayeredShaderBrush.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/interactions/InteractiveColor.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/interactions/StatefulValue.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/internal/common/Background.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/internal/common/Graphics.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/statelist/ColorValueStateList.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/statelist/NumberStateList.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/statelist/ValueStateList.kt
sdds-core/uikit/src/main/res/values/base_attrs.xml
sdds-core/uikit/src/main/res/values/value_state_list.xml

- Добавил механизм ValueStateList для Compose и XML
- Поддержал механизм в генераторах.

feat(sdds-acore): XML ValueStateList and Compose StatefulValue.

---

sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/interactions/InteractiveColor.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/interactions/StatefulValue.kt

- Исправлено обновление значения интерактивного значения при изменении состояния.

fix(sdds-acore/uikit): Fix InteractiveColor value update.

---

playground/sandbox-plasma-giga-app-integration/src/main/kotlin/com/sdds/playground/sandbox/plasma/giga/app/integration/radiobox/group/PlasmaGigaRadioBoxGroupVariationsCompose.kt
playground/sandbox-plasma-giga-integration/src/main/kotlin/com/sdds/playground/sandbox/plasma/giga/integration/radiobox/group/PlasmaGigaRadioBoxGroupVariationsCompose.kt
playground/sandbox-plasma-sd-service-integration/src/main/kotlin/com/sdds/playground/sandbox/plasma/sd/service/integration/radiobox/group/PlasmaSdServiceRadioBoxGroupVariationsCompose.kt
playground/sandbox-plasma-stards-integration/src/main/kotlin/com/sdds/playground/sandbox/plasma/stards/integration/radiobox/group/StarDsRadioBoxGroupVariationsCompose.kt
playground/sandbox-sdds-serv-integration/src/main/kotlin/com/sdds/playground/sandbox/sdds/serv/integration/radiobox/group/SddsServRadioBoxGroupVariationsCompose.kt
playground/sandbox-stylessalute-integration/src/main/kotlin/com/sdds/playground/sandbox/stylessalute/integration/radiobox/group/StylesSaluteRadioBoxGroupVariationsCompose.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/components/ComponentDelegates.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/components/radiobox/RadioBoxComposeVariationGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/components/radiobox/group/RadioBoxGroupComposeVariationGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/components/radiobox/group/RadioBoxGroupConfig.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/components/radiobox/group/RadioBoxGroupConfigDelegate.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/RadioBox.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/RadioBoxGroupStyle.kt
tokens/plasma-stards-compose/src/main/kotlin/com/sdkit/star/designsystem/styles/radioboxgroup/RadioBoxGroup.kt
tokens/plasma-stards-compose/src/main/kotlin/com/sdkit/star/designsystem/styles/radioboxgroup/RadioBoxGroupStyles.kt
tokens/plasma-stards-compose/src/main/theme-builder-res/values/style-dimens.xml
tokens/plasma.giga.app.compose/src/main/kotlin/com/sdds/plasma/giga/app/styles/radiobox/RadioBoxStyles.kt
tokens/plasma.giga.app.compose/src/main/kotlin/com/sdds/plasma/giga/app/styles/radioboxgroup/RadioBoxGroup.kt
tokens/plasma.giga.app.compose/src/main/kotlin/com/sdds/plasma/giga/app/styles/radioboxgroup/RadioBoxGroupStyles.kt
tokens/plasma.giga.compose/src/main/kotlin/com/sdds/plasma/giga/styles/radiobox/RadioBoxStyles.kt
tokens/plasma.giga.compose/src/main/kotlin/com/sdds/plasma/giga/styles/radioboxgroup/RadioBoxGroup.kt
tokens/plasma.giga.compose/src/main/kotlin/com/sdds/plasma/giga/styles/radioboxgroup/RadioBoxGroupStyles.kt
tokens/plasma.sd.service.compose/src/main/kotlin/com/sdds/plasma/sd/service/styles/radiobox/RadioBoxStyles.kt
tokens/plasma.sd.service.compose/src/main/kotlin/com/sdds/plasma/sd/service/styles/radioboxgroup/RadioBoxGroup.kt
tokens/plasma.sd.service.compose/src/main/kotlin/com/sdds/plasma/sd/service/styles/radioboxgroup/RadioBoxGroupStyles.kt
tokens/sdds.serv.compose/src/main/kotlin/com/sdds/serv/styles/radioboxgroup/RadioBoxGroup.kt
tokens/sdds.serv.compose/src/main/kotlin/com/sdds/serv/styles/radioboxgroup/RadioBoxGroupStyles.kt
tokens/stylessalute.compose/src/main/kotlin/com/sdds/stylessalute/styles/radiobox/RadioBoxStyles.kt
tokens/stylessalute.compose/src/main/kotlin/com/sdds/stylessalute/styles/radioboxgroup/RadioBoxGroup.kt
tokens/stylessalute.compose/src/main/kotlin/com/sdds/stylessalute/styles/radioboxgroup/RadioBoxGroupStyles.kt

* Реализован генератор radiobox group и сгенерированы новые стили

PLASMA-4914: radiobox-group generator was implemented

---

gradle/libs.versions.toml
playground/sandbox-compose/gradle.properties
sdds-core/plugin_theme_builder/gradle.properties
sdds-core/uikit-compose/gradle.properties
sdds-core/uikit/gradle.properties
tokens/plasma-stards-compose/gradle.properties
tokens/plasma-stards-view/gradle.properties
tokens/plasma.giga.app.compose/gradle.properties
tokens/plasma.giga.compose/gradle.properties
tokens/plasma.sd.service.compose/gradle.properties
tokens/plasma.sd.service.view/gradle.properties
tokens/sdds.serv.compose/gradle.properties
tokens/sdds.serv.view/gradle.properties
tokens/stylessalute.compose/gradle.properties
tokens/stylessalute.view/gradle.properties

Автоматический PR для обновления версий Gradle-модулей

chore: Bump versions for changed modules

---

playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/progress/compose/CircularProgressViewModel.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/CircularProgressBarStyle.kt

* Исправлен дефолтный цвет valueSuffix в CircularProgressBar
* Исправлено отображение текста значения прогресса в песочнице

fix(sdds-acore/uikit-compose): CircularProgressBar was fixed

---

tokens/plasma.giga.app.compose/src/main/kotlin/com/sdds/plasma/giga/app/styles/switcher/SwitchStyles.kt
tokens/plasma.giga.compose/src/main/kotlin/com/sdds/plasma/giga/styles/switcher/SwitchStyles.kt
tokens/plasma.sd.service.compose/src/main/kotlin/com/sdds/plasma/sd/service/styles/switcher/SwitchStyles.kt
tokens/sdds.serv.compose/src/main/kotlin/com/sdds/serv/styles/switcher/SwitchStyles.kt
tokens/stylessalute.compose/src/main/kotlin/com/sdds/stylessalute/styles/switcher/SwitchStyles.kt

fix(sdds-alibs): Switch styles were fixed

---

playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/chip/vs/group/ChipGroupParametersViewModel.kt
playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/flow/vs/FlowViewModel.kt
playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/segment/vs/group/SegmentViewModel.kt
playground/sandbox-plasma-stards-integration/src/main/kotlin/com/sdds/playground/sandbox/plasma/stards/integration/StarDsViewComponents.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/Segment.kt

- Исправил преобразование String в Int в группах в песочнице

fix(sdds-acore/sandbox): Number formatting was fixed in sandbox.

---

playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/core/vs/MenuItem.kt
playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/overlay/vs/OverlayFragment.kt
playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/overlay/vs/OverlayViewModel.kt
playground/sandbox-compose/src/main/res/values/routes.xml
playground/sandbox-core-integration/src/main/kotlin/com/sdds/playground/sandbox/core/integration/component/Component.kt
playground/sandbox-plasma-sd-service-integration/src/main/kotlin/com/sdds/playground/sandbox/plasma/sd/service/integration/PlasmaSdServiceViewComponents.kt
playground/sandbox-plasma-sd-service-integration/src/main/kotlin/com/sdds/playground/sandbox/plasma/sd/service/integration/overlay/vs/PlasmaSdServiceOverlayVariationsView.kt
playground/sandbox-plasma-stards-integration/src/main/kotlin/com/sdds/playground/sandbox/plasma/stards/integration/StarDsViewComponents.kt
playground/sandbox-plasma-stards-integration/src/main/kotlin/com/sdds/playground/sandbox/plasma/stards/integration/overlay/vs/StarDsOverlayVariationsView.kt
playground/sandbox-sdds-serv-integration/src/main/kotlin/com/sdds/playground/sandbox/sdds/serv/integration/SddsServViewComponents.kt
playground/sandbox-sdds-serv-integration/src/main/kotlin/com/sdds/playground/sandbox/sdds/serv/integration/overlay/vs/SddsServOverlayVariationsView.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/components/ComponentDelegates.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/components/overlay/OverlayConfig.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/components/overlay/OverlayConfigDelegate.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/components/overlay/view/OverlayViewStyleGenerator.kt
sdds-core/testing/src/main/kotlin/com/sdds/testing/vs/overlay/OverlayFactory.kt
sdds-core/testing/src/main/kotlin/com/sdds/testing/vs/overlay/OverlayUiState.kt
sdds-core/testing/src/main/res/values/components_id.xml
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/FrameLayout.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/OverlayView.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/statelist/ColorValueStateList.kt
sdds-core/uikit/src/main/res/values/overlay_attrs.xml
sdds-core/uikit/src/main/res/values/styles_overlay.xml
sdds-core/uikit/src/main/res/values/wrappers_attrs.xml
tokens/plasma-stards-view/src/main/theme-builder-res/values/styles-overlayview.xml
tokens/plasma.sd.service.view/src/main/theme-builder-res/values/styles-overlayview.xml
tokens/sdds.serv.view/src/main/res/values/styles_overlay_view.xml
tokens/sdds.serv.view/src/main/theme-builder-res/values/styles-overlayview.xml

- Реализован компонент OverlayView
- Реализован генератор стилей OverlayView для view system
- Сгенерированы стили в библиотеки plasma.sd.service, sdds.serv, plasma-stards
- Компонент добавлен в песочницу

PLASMA-5049: OverlayView

---

playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/core/vs/ComponentFragment.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/internal/focusselector/AnimatedSelectorDrawable.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/internal/focusselector/HasFocusSelector.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/internal/focusselector/SelectorDrawable.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/internal/textfield/DecoratedFieldBox.kt
tokens/plasma.sd.service.view/src/main/theme-builder-res/values/theme.xml
tokens/sdds.serv.view/src/main/theme-builder-res/values/theme.xml
tokens/stylessalute.view/src/main/theme-builder-res/values/theme.xml

- Исправил отображение фокус селектора в чипах компонента TextField.

PLASMA-5028: feat(sdds-acore/uikit): FocusSelector in TextField chips were fixed.

---

sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/components/textfield/view/ViewTextFieldStyleGenerator.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/TextFieldStyleBuilder.kt
tokens/plasma-stards-compose/build.gradle.kts
tokens/plasma-stards-compose/src/main/kotlin/com/sdkit/star/designsystem/styles/textarea/TextAreaClearStyles.kt
tokens/plasma-stards-compose/src/main/kotlin/com/sdkit/star/designsystem/styles/textarea/TextAreaStyles.kt
tokens/plasma-stards-compose/src/main/kotlin/com/sdkit/star/designsystem/styles/textfield/TextFieldClearStyles.kt
tokens/plasma-stards-compose/src/main/kotlin/com/sdkit/star/designsystem/styles/textfield/TextFieldStyles.kt
tokens/plasma-stards-view/src/main/theme-builder-res/color/sdkit_text_area_counter_color.xml
tokens/plasma-stards-view/src/main/theme-builder-res/color/sdkit_text_area_icon_color.xml
tokens/plasma-stards-view/src/main/theme-builder-res/color/sdkit_text_area_placeholder_color.xml
tokens/plasma-stards-view/src/main/theme-builder-res/color/sdkit_text_area_value_color.xml
tokens/plasma-stards-view/src/main/theme-builder-res/color/sdkit_text_field_counter_color.xml
tokens/plasma-stards-view/src/main/theme-builder-res/color/sdkit_text_field_icon_color.xml
tokens/plasma-stards-view/src/main/theme-builder-res/color/sdkit_text_field_placeholder_color.xml
tokens/plasma-stards-view/src/main/theme-builder-res/color/sdkit_text_field_value_color.xml

- Исправил стили TextField и TextArea в plasma-stards-view и plasma-stards-compose.

PLASMA-5039: fix(sdds-alibs/plasma-stards): TextField/TextArea styles were fixed.

---

tokens/plasma-stards-compose/src/main/theme-builder-res/values/style-dimens.xml
tokens/plasma-stards-view/src/main/theme-builder-res/values/style-dimens.xml
tokens/plasma.giga.app.compose/src/main/kotlin/com/sdds/plasma/giga/app/styles/popover/PopoverStyles.kt
tokens/plasma.giga.compose/src/main/kotlin/com/sdds/plasma/giga/styles/popover/PopoverStyles.kt
tokens/plasma.sd.service.compose/src/main/kotlin/com/sdds/plasma/sd/service/styles/popover/PopoverStyles.kt
tokens/plasma.sd.service.view/src/main/theme-builder-res/values/style-dimens.xml
tokens/sdds.serv.compose/src/main/kotlin/com/sdds/serv/styles/popover/PopoverStyles.kt
tokens/sdds.serv.view/src/main/theme-builder-res/values/style-dimens.xml
tokens/stylessalute.compose/src/main/kotlin/com/sdds/stylessalute/styles/popover/PopoverStyles.kt
tokens/stylessalute.view/src/main/theme-builder-res/values/style-dimens.xml

* Исправлен offset у Popover на compose и view system

fix(sdds-alibs): popover offset was fixed

---

playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/core/vs/SandboxActivity.kt
playground/sandbox-compose/src/main/res/values-night/themes.xml
playground/sandbox-compose/src/main/res/values/themes.xml
playground/sandbox-compose/src/starApp/res/values/themes.xml
sdds-core/testing/src/main/kotlin/com/sdds/testing/vs/Utils.kt
sdds-core/testing/src/main/res/values/test_attrs.xml
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/Popover.kt
sdds-core/uikit/src/main/res/values/styles_popover.xml

- Доработан механизм расположения Popover

fix(sdds-acore/uikit): Fixed Popover placement.

---

sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/internal/popover/BasePopover.kt

* Исправлено расположение поповера, когда нет места.

fix(sdds-acore/uikit-compose): popover fallback placement was fixed

---

playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/list/compose/ListScreen.kt
playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/textfield/compose/TextFieldScreen.kt

* Исправлена верстка экрана text field
* Убран focus selector у айтемов на экране ListScreen

fix(sdds-sandbox): text field screen was fixed. Focus selector was disabled for list screen.

---

playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/core/vs/MenuItem.kt
playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/wheel/vs/WheelFragment.kt
playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/wheel/vs/WheelViewModel.kt
playground/sandbox-compose/src/main/res/layout/layout_switch_property_item.xml
playground/sandbox-compose/src/main/res/values/routes.xml
playground/sandbox-core-integration/src/main/kotlin/com/sdds/playground/sandbox/core/integration/component/Component.kt
playground/sandbox-plasma-stards-integration/src/main/kotlin/com/sdds/playground/sandbox/plasma/stards/integration/StarDsViewComponents.kt
playground/sandbox-plasma-stards-integration/src/main/kotlin/com/sdds/playground/sandbox/plasma/stards/integration/wheel/StarDsWheelVariationsView.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/components/ComponentDelegates.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/components/wheel/WheelConfig.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/components/wheel/WheelConfigDelegate.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/components/wheel/view/WheelViewStyleGenerator.kt
sdds-core/testing/src/main/kotlin/com/sdds/testing/vs/wheel/WheelFactory.kt
sdds-core/testing/src/main/kotlin/com/sdds/testing/vs/wheel/WheelUiState.kt
sdds-core/uikit/docs/WheelUsage.md
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/CellLayout.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/Divider.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/Wheel.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/drawable/DividerDrawable.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/internal/wheel/ItemEntrySelectedListener.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/internal/wheel/WheelItemView.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/internal/wheel/WheelListView.kt
sdds-core/uikit/src/main/res/layout/sd_layout_wheel_item.xml
sdds-core/uikit/src/main/res/values/styles_wheel.xml
sdds-core/uikit/src/main/res/values/wheel_attrs.xml
tokens/plasma-stards-view/src/main/res/values/themes.xml
tokens/plasma-stards-view/src/main/theme-builder-res/color/sdkit_wheel_control_down_color.xml
tokens/plasma-stards-view/src/main/theme-builder-res/color/sdkit_wheel_control_up_color.xml
tokens/plasma-stards-view/src/main/theme-builder-res/values/style-dimens.xml
tokens/plasma-stards-view/src/main/theme-builder-res/values/styles-wheel.xml

- Реализован компонент Wheel
- Реализован генератор стилей Wheel для view system.
- Компонент Wheel добавлен в песочницу.
https://github.com/user-attachments/assets/9a7e4c6c-6b7d-4a79-aa77-7c45adf83b3b

PLASMA-5233: Wheel.

---

.github/workflows/clean-docs-pr.yml

- Исправлен workflow очистки ПРа

ci: Clean Docs on PR workflow was fixed.

---

.github/workflows/publish-sandbox-compose.yml
build-system/conventions/src/main/kotlin/utils/DocsProjectUtils.kt
playground/sandbox-compose/build.gradle.kts
playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/core/updates/UpdateChecker.kt
tokens/plasma-stards-compose/override-docs/versionsArchived.json
tokens/plasma-stards-view/override-docs/versionsArchived.json
tokens/plasma.giga.app.compose/override-docs/versionsArchived.json
tokens/plasma.giga.compose/override-docs/versionsArchived.json
tokens/plasma.sd.service.compose/override-docs/versionsArchived.json
tokens/plasma.sd.service.view/override-docs/versionsArchived.json
tokens/sdds.serv.compose/override-docs/versionsArchived.json
tokens/sdds.serv.view/override-docs/versionsArchived.json
tokens/stylessalute.compose/override-docs/versionsArchived.json
tokens/stylessalute.view/override-docs/versionsArchived.json

-История версий документации токенов исправлена.

fix: Tokens documentation version history were fixed.

---

sdds-core/uikit/src/main/kotlin/com/sdds/uikit/Button.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/CheckBox.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/Chip.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/Counter.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/RadioBox.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/Switch.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/TextField.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/internal/CheckBoxDrawable.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/internal/RadioBoxDrawable.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/internal/SwitchDrawable.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/internal/base/Utils.kt
sdds-core/uikit/src/main/res/values/checkable_attrs.xml

- Добавил поддержку установки xfermode для иконок маркера в CheckBox и RadioBox, а также для thumb в Switch.

fix(sdds-acore/uikit): Switch, CheckBox and RadioBox tintMode support was added.

---

sdds-core/uikit/src/main/kotlin/com/sdds/uikit/internal/wheel/WheelItemView.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/internal/wheel/WheelListView.kt

-   Исправлено поведение колбэка Wheel.EntrySelectedListener в режиме бесконечного скролла. 
В режиме бесконечного скролла не срабатывал колбэк Wheel.EntrySelectedListener из-за некорректно рассчитанной текущей позиции. Этот ПР исправляет эту ошибку. Также в данном ПРе доработано поведение при динамическом изменении description.

PLASMA-5738: fix(sdds-acore/uikit): Wheel selection callback was fixed.

---

playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/buttons/compose/BasicButtonScreen.kt
playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/buttons/compose/IconButtonScreen.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/Button.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/internal/BaseButton.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/internal/common/Modifiers.kt

-   Добавлена поддержка ресурсов иконок в Button вместо painter.
Добавлена перегрузка IconButton с ресурсом иконки, вместо painter. В классе ButtonIcons параметры с Painter помечены как deprecated и добавлены параметры с ресурсами

PLASMA-5811: feat(sdds-acore/uikit-compose): Compose button improvement

---

sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/TextSkeleton.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/internal/Utils.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/FrameLayout.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/ShimmerLayout.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/TextSkeleton.kt
sdds-core/uikit/src/main/res/values/skeleton_attrs.xml

-   Исправлен алгоритм расчета размеров линии
-  Исправлен алгоритм расчета размеров линии 
Размеры линии TextSkeleton теперь рассчитываются на основе метрик шрифта. 
https://github.com/user-attachments/assets/73d191a4-c8b9-43f9-9245-acb4efa83090
https://github.com/user-attachments/assets/dead26d7-13e6-4d9b-8420-a57a9ff940a3

PLASMA-5751: PLASMA-5752: TextSkeleton text metrics calculation fixed

---

build-system/docs-template/compose-template/docs/components/WheelUsage.md
playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/core/compose/MenuItem.kt
playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/wheel/compose/WheelScreen.kt
playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/wheel/compose/WheelUiState.kt
playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/wheel/compose/WheelViewModel.kt
playground/sandbox-plasma-homeds-integration/src/main/kotlin/com/sdds/playground/sandbox/plasma/homeds/integration/PlasmaHomeDsComposeComponents.kt
playground/sandbox-plasma-homeds-integration/src/main/kotlin/com/sdds/playground/sandbox/plasma/homeds/integration/wheel/PlasmaHomeDsWheelVariationsCompose.kt
playground/sandbox-plasma-stards-integration/src/main/kotlin/com/sdds/playground/sandbox/plasma/stards/integration/StarDsComposeComponents.kt
playground/sandbox-plasma-stards-integration/src/main/kotlin/com/sdds/playground/sandbox/plasma/stards/integration/wheel/StarDsWheelVariationsCompose.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/components/wheel/WheelConfig.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/components/wheel/WheelConfigDelegate.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/components/wheel/compose/WheelComposeVariationGenerator.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/Wheel.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/WheelStyle.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/internal/wheel/BaseWheel.kt
tokens/plasma-stards-compose/gradle.properties
tokens/plasma-stards-compose/src/main/kotlin/com/sdkit/star/designsystem/styles/wheel/Wheel.kt
tokens/plasma-stards-compose/src/main/kotlin/com/sdkit/star/designsystem/styles/wheel/WheelStyles.kt
tokens/plasma-stards-compose/src/main/theme-builder-res/values/style-dimens.xml
tokens/plasma.homeds.compose/gradle.properties
tokens/plasma.homeds.compose/src/main/kotlin/com/sdds/plasma/homeds/styles/wheel/Wheel.kt
tokens/plasma.homeds.compose/src/main/kotlin/com/sdds/plasma/homeds/styles/wheel/WheelStyles.kt

- Реализован компонент Wheel
- Добавлены стили компонентов Wheel
- Добавлены стили компонентов Wheel
Реализован компонент Wheel и генератор компонента на compose. Сгенерированы стили. Компонент добавлен в песочницу. Написана документация.
https://github.com/user-attachments/assets/00975cf4-e057-4e99-82ef-f1a42fb5ee1d

feat(sdds-acore/uikit-compose): Wheel was implemented for compose
