.github/workflows/android-code-quality-check.yml
.github/workflows/build-debug.yml
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/ColorGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/GradientGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/TypographyGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/serializer/ExcludeNonAndroidPlatformTokens.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/serializer/Serializer.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/serializer/UnknownTypeSerializer.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/token/TypographyTokens.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/utils/StringUtils.kt
sdds-core/plugin_theme_builder/src/test/kotlin/com/sdds/plugin/themebuilder/internal/utils/StringUtilsKtTest.kt
sdds-core/plugin_theme_builder/src/test/resources/color-outputs/TestColorOutputKt.txt

What changed: 
- Default serializer was added. Compose generator color format was changed from rgba to argb;
- Dispatch conditions were extended for lint, test and build workflows.

feat(sdds-acore/theme-builder): Theme-builder colors

---

sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/FetchPaletteTask.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/GenerateThemeTask.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/ThemeBuilderExtension.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/ThemeBuilderPlugin.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/factory/GeneratorFactory.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/ColorTokenGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/GradientGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/theme/compose/ComposeColorAttributeGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/theme/compose/ComposeGradientAttributeGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/theme/compose/ComposeShapeAttributeGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/utils/ColorUtils.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/utils/StringUtils.kt
sdds-core/plugin_theme_builder/src/test/kotlin/com/sdds/plugin/themebuilder/internal/generator/ColorTokenGeneratorTest.kt
sdds-core/plugin_theme_builder/src/test/kotlin/com/sdds/plugin/themebuilder/internal/generator/GradientGeneratorTest.kt
sdds-core/plugin_theme_builder/src/test/kotlin/com/sdds/plugin/themebuilder/internal/utils/ColorUtilsKtTest.kt
sdds-core/plugin_theme_builder/src/test/kotlin/com/sdds/plugin/themebuilder/internal/utils/StringUtilsKtTest.kt
sdds-core/plugin_theme_builder/src/test/resources/color-outputs/TestColorOutputKt.txt
sdds-core/plugin_theme_builder/src/test/resources/color-outputs/test-color-output.xml
sdds-core/plugin_theme_builder/src/test/resources/inputs/test-color-input.json

* Реализовал поддержку цветовой палитры для темы. Палитра качается в отдельной таске, на которую зависят последующие таски по выкачке темы.
* Расширил утилиту по переводу цвета в argb формат, добавил поддержку хекса с решеткой для xml.

feat(sdds-acore/theme-builder): Color palette support

---

sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/ShapeTokenGenerator.kt

* Пофиксил генерацию shape токенов, когда выключена генерация стилей shape для view

fix(sdds-acore/theme-builder): Fixed compose shape tokens

---

sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/builder/KtFileBuilder.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/TypographyTokenGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/validator/ColorTokenValidator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/validator/ShadowTokenValidator.kt
sdds-core/plugin_theme_builder/src/test/kotlin/com/sdds/plugin/themebuilder/internal/validator/ColorTokenValidatorTest.kt
sdds-core/plugin_theme_builder/src/test/kotlin/com/sdds/plugin/themebuilder/internal/validator/ShadowTokenValidatorTest.kt
sdds-core/plugin_theme_builder/src/test/resources/typography-outputs/TestTypographyOutputKt.txt
tokens/caldera.online.compose/build.gradle.kts
tokens/flamingo.compose/build.gradle.kts
tokens/plasma.b2c.compose/build.gradle.kts
tokens/plasma.web.compose/build.gradle.kts
tokens/sberhealth.compose/build.gradle.kts
tokens/sbermarket.business.compose/build.gradle.kts
tokens/sbermarket.compose/build.gradle.kts
tokens/sbermarket.metro.compose/build.gradle.kts
tokens/sbermarket.selgros.compose/build.gradle.kts
tokens/sbermarket.wlbusiness.compose/build.gradle.kts
tokens/sberonline.compose/build.gradle.kts
tokens/sberprime.compose/build.gradle.kts
tokens/sdds.serv.compose/build.gradle.kts
tokens/stylessalute.compose/build.gradle.kts

* Добавил фикс LineHeight в Compose токены типографики
* Добавил потерявшуюся проверку цвета для токенов теней
* Закоммитил исправления отступов в модулях tokens

feat(sdds-acore/theme-builder): Improve compose typography tokens with lineHeight support

---

sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/theme/compose/ComposeColorAttributeGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/theme/compose/ComposeGradientAttributeGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/theme/compose/ComposeShapeAttributeGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/theme/compose/ComposeThemeGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/theme/compose/ComposeTypographyAttributeGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/theme/view/ViewGradientAttributeGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/theme/view/ViewThemeGenerator.kt
sdds-core/plugin_theme_builder/src/test/kotlin/com/sdds/plugin/themebuilder/internal/generator/theme/ViewThemeGeneratorTest.kt
sdds-core/plugin_theme_builder/src/test/resources/theme-outputs/test-theme-output.xml

* Поправил наименования функций и классов в файлах с атрибутами для compose. Теперь любой themeName сначала приводится к СamelCase и потом используется в генерируемом коде.
* Также добавил рутовый стиль состоящий из ResPrefix, даже если генерируется тема, а не только токены.

fix(sdds-acore/theme-builder): Fix color and gradient fun names

---

sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/GenerateThemeTask.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/download/FontDownloader.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/factory/GeneratorFactory.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/fonts/FontData.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/fonts/FontsAggregator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/FontTokenGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/TypographyTokenGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/utils/ResourceReferenceProvider.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/utils/StringUtils.kt
sdds-core/plugin_theme_builder/src/test/kotlin/com/sdds/plugin/themebuilder/internal/fonts/FontsAggregatorTest.kt
sdds-core/plugin_theme_builder/src/test/kotlin/com/sdds/plugin/themebuilder/internal/generator/FontTokenGeneratorTest.kt
sdds-core/plugin_theme_builder/src/test/kotlin/com/sdds/plugin/themebuilder/internal/generator/TypographyTokenGeneratorTest.kt
sdds-core/plugin_theme_builder/src/test/kotlin/com/sdds/plugin/themebuilder/internal/utils/ResourceReferenceProviderTest.kt
sdds-core/plugin_theme_builder/src/test/resources/typography-outputs/test-appearances-large-output.xml
sdds-core/plugin_theme_builder/src/test/resources/typography-outputs/test-appearances-output.xml
sdds-core/plugin_theme_builder/src/test/resources/typography-outputs/test-appearances-small-output.xml

* Исправлена проблема, когда не работает fontStyle на api < 28. В каждый стиль добавляется атрибут textFontWeight, и и в качестве fontFamily указывается не ссылка на ресурс fontFamily а ссылка на файл шрифта
Ниже скриншоты на эмуляторах с 24 и 33 api level

feat(sdds-acore/theme-builder): Support font style for low api levels

---

playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/chip/SandboxChip.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/Chip.kt

* Исправил кейс, когда текста много, и иконка справа уменьшается в размерах, пока совсем не пропадет
* Поменял api компонента таким образом, чтобы для текста лямбда не передавалась, а передавалась только строка с текстом и текстовый стиль
было / стало

fix(sdds-acore/uikit-compose): chip icon size fix

---

playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/textarea/TextAreaDefaults.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/internal/textarea/TextAreaLayout.kt

* Исправил отступ в text area в конце, учтены кейсы когда иконка есть и когда нет
* В расчете ширины text area учитываются ширина counter и caption
https://github.com/user-attachments/assets/1ad3df6c-9893-412d-b140-86d59a752126

fix(sdds-acore/uikit-compose): fix text area paddings

---

sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/internal/BaseButton.kt

* Исправил проблему, когда текст при переполнении заезжал на иконку справа в режиме spacing == Packed
https://github.com/user-attachments/assets/d34c2387-86e4-4f17-b9d2-c750d89ba545

fix(sdds-acore/uikit-compose): button text was fixed

---

playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/textfield/TextFieldScreen.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/theme/compose/ComposeThemeGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/generator/theme/compose/ComposeTypographyAttributeGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/token/GradientTokens.kt
sdds-core/plugin_theme_builder/src/test/resources/attrs-outputs/TypographyOutputKt_1.txt
sdds-core/plugin_theme_builder/src/test/resources/attrs-outputs/TypographyOutputKt_2.txt
sdds-core/plugin_theme_builder/src/test/resources/attrs-outputs/TypographyOutputKt_3.txt
sdds-core/plugin_theme_builder/src/test/resources/theme-outputs/ThemeOutputKt.txt
sdds-core/plugin_theme_builder/src/test/resources/theme-outputs/ThemeOutputKtWithTextSelectionAndTextStyle.txt

* Убрал ручную установку цвета иконкам в text field в песочнице, чтобы работал LocalTint
* Убрал генерацию проперти LocalTextStyle и функции ProvideTextStyle(). В теме теперь делается вызов одноименной функции из uikit и теперь этот механизм работает и все компоненты Text обеспечены дефолтным стилем из темы.

feat(sdds-acore/uikit-compose): setup local text style

---

sdds-core/plugin_theme_builder/gradle.properties
sdds-core/uikit-compose/gradle.properties
sdds-core/uikit/gradle.properties

sdds-core uikit, uikit compose and plugin_theme-builder versions were bumped.

chore: Versions bump

---

sdds-core/uikit/src/main/kotlin/com/sdds/uikit/internal/focusselector/HasFocusSelector.kt

Border focus selector insets were fixed.

fix(sdds-acore/uikit): Focus selector.

---

.github/scripts/testfairy-uploader.sh
.github/workflows/publish-icons-release.yml
.github/workflows/publish-sandbox-compose.yml
.github/workflows/publish-sandbox.yml
.github/workflows/publish-uikit-compose-release.yml
.github/workflows/publish-uikit-release.yml
build-system/conventions/src/main/kotlin/convention.maven-publish.gradle.kts

- Sandbox applications releases now can be distributed to testes via TestFairy. 
- Library publishing workflows were improved: release artifacts are now automatically attached to GitHub Releases and automatically published at MavenCentral.

build: Artifact distribution workflows.

---

tokens/build.gradle.kts

отключил spotlessApplyAll для библиотек из модуля tokens

fix(sdds-alibs/plasmab2c): disable spotlessApplyAll for tokens libs

---

playground/sandbox/src/main/kotlin/com/sdds/playground/sandbox/core/view/ComponentFragment.kt
playground/sandbox/src/main/res/color-night/bg_cell_switch_track.xml
playground/sandbox/src/main/res/color-night/bg_color_property_switch_track.xml
playground/sandbox/src/main/res/color-night/color_cell_checkable_border.xml
playground/sandbox/src/main/res/color-night/color_cell_text.xml
playground/sandbox/src/main/res/layout/fragment_component_scaffold.xml
playground/sandbox/src/main/res/layout/layout_component_cell.xml
playground/sandbox/src/main/res/values/styles_chip.xml
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/CellLayout.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/CheckBoxGroup.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/FlowLayout.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/LinearLayout.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/TextField.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/internal/base/ClipOutlineCompat.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/internal/textfield/DecoratedFieldBox.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/shape/ShapeDrawable.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/shape/Shapeable.kt
sdds-core/uikit/src/main/res/values/base_attrs.xml
sdds-core/uikit/src/main/res/values/button_attrs.xml
sdds-core/uikit/src/main/res/values/cell_layout_attrs.xml
sdds-core/uikit/src/main/res/values/chip_attrs.xml
sdds-core/uikit/src/main/res/values/flow_layout_attrs.xml
sdds-core/uikit/src/main/res/values/image_view_attrs.xml
sdds-core/uikit/src/main/res/values/wrappers_attrs.xml

Focus selector was added to all viewgroups.

feat(sdds-acore/uikit): Focus selector in ViewGroup

---

sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/internal/textfield/BaseTextField.kt

* Исправил некорректное поведение text field при достижении ограничения
https://github.com/user-attachments/assets/f2f42f48-a3c0-4c16-a9a7-6efb7c0939f4

fix(sdds-acore/uikit-compose): fix text field height

---

sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/builder/KtFileBuilder.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/components/ComposeComponentStyleGenerator.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/components/button/BaseButtonStyleGeneratorCompose.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/components/button/BasicButtonStyleGeneratorCompose.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/components/button/IconButtonStyleGeneratorCompose.kt
sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/components/button/LinkButtonStyleGeneratorCompose.kt
sdds-core/plugin_theme_builder/src/test/kotlin/com/sdds/plugin/themebuilder/internal/components/button/BasicButtonStyleGeneratorComposeTest.kt
sdds-core/plugin_theme_builder/src/test/kotlin/com/sdds/plugin/themebuilder/internal/components/button/IconButtonStyleGeneratorComposeTest.kt
sdds-core/plugin_theme_builder/src/test/kotlin/com/sdds/plugin/themebuilder/internal/components/button/LinkButtonStyleGeneratorComposeTest.kt
sdds-core/plugin_theme_builder/src/test/resources/component-outputs/BasicButtonStylesKt.txt
sdds-core/plugin_theme_builder/src/test/resources/component-outputs/IconButtonStylesKt.txt
sdds-core/plugin_theme_builder/src/test/resources/component-outputs/LinkButtonStylesKt.txt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/BasicButtonStyleBuilder.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/Button.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/ButtonStyles.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/IconButtonStyleBuilder.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/LinkButtonStyleBuilder.kt
tokens/plasma.sd.service.compose/src/main/kotlin/com/sdds/plasma/sd/service/styles/button/link/LinkButtonStyles.kt
tokens/sdds.serv.compose/src/main/kotlin/com/sdds/serv/styles/button/link/LinkButtonStyles.kt

* Реализована генерация вариаций цвета кнопок на Cоmpose
* spinnerMode перенесен из билдера стиля в билдер цвета, т.к. режим спиннера напрямую зависит от цвета, но не от размера

feat(sdds-acore/theme-builder): generate color variations for compose button

---

playground/sandbox-compose/src/test/kotlin/com/sdds/playground/sandbox/compose/ComposeTextAreaScreenshotTest.kt
playground/sandbox-compose/src/test/kotlin/com/sdds/playground/sandbox/compose/ComposeTextFieldScreenshotTest.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/internal/common/Modifiers.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/internal/textfield/BaseTextField.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/internal/textfield/DecorationBox.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/internal/textfield/TextFieldLayout.kt

* Убрал использование декоратора в системном BasicTextField, чтобы сделать focusable внутренние сущности DecorationBox. Вместо этого просто положил BasicTextField внутрь декоратора.
* Добавил логику установки фокуса в textField, если кликать по DecorationBox
* Доработал тесты с фокусным состоянием, добавил теги для внутреннего textField и для внешнего контейнера (DecorationBox)
https://github.com/user-attachments/assets/e8bff9ee-959c-42cb-a94a-00063766ae09
https://github.com/user-attachments/assets/d5b7ab4d-f7c8-4720-b75f-d74ef1340ee6

feat(sdds-acore/uikit-compose): fix inner tf focus

---

build-system/conventions/src/main/kotlin/utils/AutoBump.kt

Поправил воркфлоу апдейта иконок. Он не срабатывал, потому что в таске AutoBump появился новый функционал с кешированием версии в build директории, который не учитывал то, что build директория может не существовать
https://github.com/salute-developers/plasma-android/actions/workflows/generate-icons.yml

ci: icon workflow was fixed

---

playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/activities/vs/SandboxActivity.kt
tokens/plasma-stards-view/src/main/res/values/styles_navigation_drawer.xml
tokens/sdds.serv.view/src/main/res/values/styles_navigation_drawer.xml

- NavigationDrawer selection animation was disabled.
- Sandbox now can save and restore last fragment when switching themes.

fix(sdds-alibs): NavigationDrawer

---

build-system/gradle.properties
gradle.properties
playground/gradle.properties
sdds-core/gradle.properties
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/AccordionItem.kt
sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/internal/textfield/TextFieldLayout.kt
tokens/plasma.giga.app.compose/src/main/kotlin/com/sdds/plasma/giga/app/styles/accordionitem/AccordionItemClearActionEndStyles.kt
tokens/plasma.giga.app.compose/src/main/kotlin/com/sdds/plasma/giga/app/styles/accordionitem/AccordionItemClearActionStartStyles.kt
tokens/plasma.giga.app.compose/src/main/kotlin/com/sdds/plasma/giga/app/styles/accordionitem/AccordionItemSolidActionEndStyles.kt
tokens/plasma.giga.app.compose/src/main/kotlin/com/sdds/plasma/giga/app/styles/accordionitem/AccordionItemSolidActionStartStyles.kt
tokens/plasma.giga.compose/src/main/kotlin/com/sdds/plasma/giga/styles/accordionitem/AccordionItemClearActionEndStyles.kt
tokens/plasma.giga.compose/src/main/kotlin/com/sdds/plasma/giga/styles/accordionitem/AccordionItemClearActionStartStyles.kt
tokens/plasma.giga.compose/src/main/kotlin/com/sdds/plasma/giga/styles/accordionitem/AccordionItemSolidActionEndStyles.kt
tokens/plasma.giga.compose/src/main/kotlin/com/sdds/plasma/giga/styles/accordionitem/AccordionItemSolidActionStartStyles.kt
tokens/plasma.sd.service.compose/src/main/kotlin/com/sdds/plasma/sd/service/styles/accordionitem/AccordionItemClearActionEndStyles.kt
tokens/plasma.sd.service.compose/src/main/kotlin/com/sdds/plasma/sd/service/styles/accordionitem/AccordionItemClearActionStartStyles.kt
tokens/plasma.sd.service.compose/src/main/kotlin/com/sdds/plasma/sd/service/styles/accordionitem/AccordionItemSolidActionEndStyles.kt
tokens/plasma.sd.service.compose/src/main/kotlin/com/sdds/plasma/sd/service/styles/accordionitem/AccordionItemSolidActionStartStyles.kt
tokens/sdds.serv.compose/src/main/kotlin/com/sdds/serv/styles/accordionitem/AccordionItemClearActionEndStyles.kt
tokens/sdds.serv.compose/src/main/kotlin/com/sdds/serv/styles/accordionitem/AccordionItemClearActionStartStyles.kt
tokens/sdds.serv.compose/src/main/kotlin/com/sdds/serv/styles/accordionitem/AccordionItemSolidActionEndStyles.kt
tokens/sdds.serv.compose/src/main/kotlin/com/sdds/serv/styles/accordionitem/AccordionItemSolidActionStartStyles.kt
tokens/stylessalute.compose/src/main/kotlin/com/sdds/stylessalute/styles/accordionitem/AccordionItemClearActionEndStyles.kt
tokens/stylessalute.compose/src/main/kotlin/com/sdds/stylessalute/styles/accordionitem/AccordionItemClearActionStartStyles.kt
tokens/stylessalute.compose/src/main/kotlin/com/sdds/stylessalute/styles/accordionitem/AccordionItemSolidActionEndStyles.kt
tokens/stylessalute.compose/src/main/kotlin/com/sdds/stylessalute/styles/accordionitem/AccordionItemSolidActionStartStyles.kt

* Исправлено скругление контейнера чипов в textfield
* Добален iconColor в AccordionItem

fix(sdds-acore/uikit-compose): AccordionItem iconColor was fixed. TextField chips radius was fixed

---

sdds-core/uikit/src/main/kotlin/com/sdds/uikit/SegmentItem.kt

Исправлена ошибка отрисовки Counter в превью SegmentItem в случае, если компонент настраивается через xml.

PLASMA-5480: Rendering of the Counter in the SegmentItem xml preview was fixed.

---

sdds-core/uikit/src/main/kotlin/com/sdds/uikit/Badge.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/IconBadge.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/drawable/BadgeDrawable.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/drawable/IconBadgeDrawable.kt
sdds-core/uikit/src/main/kotlin/com/sdds/uikit/drawable/TextDrawable.kt

Удалена возможность задать текст в IconBadge через xml

PLASMA-5479: Displaying and assigning text through xml in IconBadge was fixed

---

sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/fs/FocusSelectorSettings.kt

-   Исправлено некорректное поведение модификатора focusSelector().
При применении focusSelector() он некорректно смешивал всю цепочку модификаторов до него с такой же цепочкой плюс модифкатор скейла / бордера. Это приводило к двойному/тройному применению всей цепочки, и если в ней были паддинги, они увеличивались в 2-3 раза.

PLASMA-5761: fix(sdds-acore/uikit-compose): apply focus selector modifiers in right way

---

tokens/plasma-stards-compose/src/main/kotlin/com/sdkit/star/designsystem/DimensionUtils.kt
tokens/plasma-stards-compose/src/main/res/values/dimens.xml

- Добавлены extension свойства .dp и .sp. Теперь можно указывать dimensions в коде, не заботясь о ресурсах для альтернативных размеров экранов - расчет происходит автоматически.
- Добавил эталонные dimensions для расчета dp и sp в коде. Плагин для dimensions подготовит альтернативы для эталонных dimensions и в коде будут использованы корректные размеры.

PLASMA-5905: feat(sdds-alibs/plasma-star-ds): Add extensions for scaled dp and sp.
